/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CvOuvrierRouteImport } from './routes/cv-ouvrier'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CvIdRouteImport } from './routes/cv.$id'
import { Route as CvIdPrintRouteImport } from './routes/cv.$id.print'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CvOuvrierRoute = CvOuvrierRouteImport.update({
  id: '/cv-ouvrier',
  path: '/cv-ouvrier',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CvIdRoute = CvIdRouteImport.update({
  id: '/cv/$id',
  path: '/cv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CvIdPrintRoute = CvIdPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => CvIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv-ouvrier': typeof CvOuvrierRoute
  '/login': typeof LoginRoute
  '/cv/$id': typeof CvIdRouteWithChildren
  '/cv/$id/print': typeof CvIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv-ouvrier': typeof CvOuvrierRoute
  '/login': typeof LoginRoute
  '/cv/$id': typeof CvIdRouteWithChildren
  '/cv/$id/print': typeof CvIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv-ouvrier': typeof CvOuvrierRoute
  '/login': typeof LoginRoute
  '/cv/$id': typeof CvIdRouteWithChildren
  '/cv/$id/print': typeof CvIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cv-ouvrier' | '/login' | '/cv/$id' | '/cv/$id/print'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cv-ouvrier' | '/login' | '/cv/$id' | '/cv/$id/print'
  id: '__root__' | '/' | '/cv-ouvrier' | '/login' | '/cv/$id' | '/cv/$id/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvOuvrierRoute: typeof CvOuvrierRoute
  LoginRoute: typeof LoginRoute
  CvIdRoute: typeof CvIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv-ouvrier': {
      id: '/cv-ouvrier'
      path: '/cv-ouvrier'
      fullPath: '/cv-ouvrier'
      preLoaderRoute: typeof CvOuvrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv/$id': {
      id: '/cv/$id'
      path: '/cv/$id'
      fullPath: '/cv/$id'
      preLoaderRoute: typeof CvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv/$id/print': {
      id: '/cv/$id/print'
      path: '/print'
      fullPath: '/cv/$id/print'
      preLoaderRoute: typeof CvIdPrintRouteImport
      parentRoute: typeof CvIdRoute
    }
  }
}

interface CvIdRouteChildren {
  CvIdPrintRoute: typeof CvIdPrintRoute
}

const CvIdRouteChildren: CvIdRouteChildren = {
  CvIdPrintRoute: CvIdPrintRoute,
}

const CvIdRouteWithChildren = CvIdRoute._addFileChildren(CvIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvOuvrierRoute: CvOuvrierRoute,
  LoginRoute: LoginRoute,
  CvIdRoute: CvIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
